---
version: 2
jobs:
  docs-lint:
    docker:
      - image: quay.io/freedomofpress/circleci-docker:latest

    steps:
      - checkout

      - run:
          name: Installation pre-reqs
          command: pip install -U -r securedrop/requirements/develop-requirements.txt

      - run:
          name: Run docs lint
          command: make docs-lint

  build-debs:
    docker:
      - image: quay.io/freedomofpress/circleci-docker:latest
    working_directory: ~/sd
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: ~/sd

      - run:
          name: Installation pre-reqs
          command: pip install -U -r ./testinfra/requirements.txt

      - run:
          name: Run docs lint
          command: make build-debs

      - persist_to_workspace:
          root: .
          paths:
            - build

  staging-test:
    docker:
      - image: quay.io/freedomofpress/circleci-docker:latest
        environment:
          FPF_CI: true
          CI_SD_ENV: staging
          CI_AWS_TYPE: t2.small
          FPF_GRSEC: false
          TEST_REPORTS: /root/sd
    working_directory: ~/sd

    steps:

      - checkout
      - attach_workspace:
          at: ~/sd

      - setup_remote_docker

      - run:
          name: Installation pre-reqs
          command: pip install -U -r ./testinfra/requirements.txt

      - run:
          name: Run molecule and manage tests
          command: make ci-go

      - run:
          name: Ensure environment torn down
          command: molecule destroy -s aws
          when: always

      - store_test_results:
          path: /root/sd/junit

      - store_artifacts:
          path: /root/sd/junit

workflows:
  version: 2
  securedrop_ci:
    jobs:
      - docs-lint
      - build-debs
      - staging-test:
          requires:
            - docs-lint
            - build-debs
