---
#This role is to check that development and staging defaults gpg info and
#credentials are not used when running the app and mon playbooks for
#production.

- include: validate_users.yml

- include: validate_gpg_info.yml
  with_items:
    - keyfile: "{{ ossec_alert_gpg_public_key }}"
      fingerprint: "{{ ossec_gpg_fpr|replace(" ","") }}"

    - keyfile: "{{ securedrop_app_gpg_public_key }}"
      fingerprint: "{{ securedrop_app_gpg_fingerprint|replace(" ","") }}"

- include: validate_ossec_info.yml

- include: validate_tails_environment.yml
  when: securedrop_validate_tails_environment
